ran aclocal and autorecong

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -805,6 +805,8 @@ acx_pthread_config
 XMKMF
 LIBOBJS
 ALLOCA
+GTHREAD_LIBS
+GTHREAD_CFLAGS
 GTK_LIBS
 GTK_CFLAGS
 PKG_CONFIG
@@ -940,6 +942,8 @@ CPP
 PKG_CONFIG
 GTK_CFLAGS
 GTK_LIBS
+GTHREAD_CFLAGS
+GTHREAD_LIBS
 XMKMF
 CXX
 CXXFLAGS
@@ -1608,6 +1612,10 @@ Some influential environment variables:
   PKG_CONFIG  path to pkg-config utility
   GTK_CFLAGS  C compiler flags for GTK, overriding pkg-config
   GTK_LIBS    linker flags for GTK, overriding pkg-config
+  GTHREAD_CFLAGS
+              C compiler flags for GTHREAD, overriding pkg-config
+  GTHREAD_LIBS
+              linker flags for GTHREAD, overriding pkg-config
   XMKMF       Path to xmkmf, Makefile generator for X Window System
   CXX         C++ compiler command
   CXXFLAGS    C++ compiler flags
@@ -4035,13 +4043,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:4038: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:4046: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4041: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:4049: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:4044: output\"" >&5)
+  (eval echo "\"\$as_me:4052: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -5247,7 +5255,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5250 "configure"' > conftest.$ac_ext
+  echo '#line 5258 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7104,11 +7112,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7107: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7115: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7111: \$? = $ac_status" >&5
+   echo "$as_me:7119: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7443,11 +7451,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7446: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7454: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7450: \$? = $ac_status" >&5
+   echo "$as_me:7458: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7548,11 +7556,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7551: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7559: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7555: \$? = $ac_status" >&5
+   echo "$as_me:7563: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7603,11 +7611,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7606: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7614: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7610: \$? = $ac_status" >&5
+   echo "$as_me:7618: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10403,7 +10411,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10406 "configure"
+#line 10414 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10499,7 +10507,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 10502 "configure"
+#line 10510 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12593,25 +12601,23 @@ fi
 
 	{ $as_echo "$as_me:$LINENO: result: no" >&5
 $as_echo "no" >&6; }
-                { { $as_echo "$as_me:$LINENO: error:
+                { $as_echo "$as_me:$LINENO:
 *** GTK+ 2.0 is not required to build Funk2, but the GLib development headers
 *** are not installed, so GTK support will not be compiled into Funk2.  The
 *** latest version of GLib is always available at http://www.gtk.org" >&5
-$as_echo "$as_me: error:
+$as_echo "$as_me:
 *** GTK+ 2.0 is not required to build Funk2, but the GLib development headers
 *** are not installed, so GTK support will not be compiled into Funk2.  The
-*** latest version of GLib is always available at http://www.gtk.org" >&2;}
-   { (exit 1); exit 1; }; }
+*** latest version of GLib is always available at http://www.gtk.org" >&6;}
 elif test $pkg_failed = untried; then
-	{ { $as_echo "$as_me:$LINENO: error:
+	{ $as_echo "$as_me:$LINENO:
 *** GTK+ 2.0 is not required to build Funk2, but the GLib development headers
 *** are not installed, so GTK support will not be compiled into Funk2.  The
 *** latest version of GLib is always available at http://www.gtk.org" >&5
-$as_echo "$as_me: error:
+$as_echo "$as_me:
 *** GTK+ 2.0 is not required to build Funk2, but the GLib development headers
 *** are not installed, so GTK support will not be compiled into Funk2.  The
-*** latest version of GLib is always available at http://www.gtk.org" >&2;}
-   { (exit 1); exit 1; }; }
+*** latest version of GLib is always available at http://www.gtk.org" >&6;}
 else
 	GTK_CFLAGS=$pkg_cv_GTK_CFLAGS
 	GTK_LIBS=$pkg_cv_GTK_LIBS
@@ -12620,6 +12626,98 @@ $as_echo "yes" >&6; }
 
 cat >>confdefs.h <<\_ACEOF
 #define F2__GTK_SUPPORTED 1
+_ACEOF
+
+fi
+
+
+
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for GTHREAD" >&5
+$as_echo_n "checking for GTHREAD... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GTHREAD_CFLAGS"; then
+        pkg_cv_GTHREAD_CFLAGS="$GTHREAD_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gthread-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gthread-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTHREAD_CFLAGS=`$PKG_CONFIG --cflags "gthread-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$GTHREAD_LIBS"; then
+        pkg_cv_GTHREAD_LIBS="$GTHREAD_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"gthread-2.0\"") >&5
+  ($PKG_CONFIG --exists --print-errors "gthread-2.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_GTHREAD_LIBS=`$PKG_CONFIG --libs "gthread-2.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        GTHREAD_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "gthread-2.0"`
+        else
+	        GTHREAD_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "gthread-2.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$GTHREAD_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+                { $as_echo "$as_me:$LINENO:
+*** GTHREAD 2.0 is not required to build Funk2, but the Gthread development headers
+*** are not installed, so GTHREAD support will not be compiled into Funk2.  The
+*** latest version of Gthread is always available at http://www.gtk.org" >&5
+$as_echo "$as_me:
+*** GTHREAD 2.0 is not required to build Funk2, but the Gthread development headers
+*** are not installed, so GTHREAD support will not be compiled into Funk2.  The
+*** latest version of Gthread is always available at http://www.gtk.org" >&6;}
+elif test $pkg_failed = untried; then
+	{ $as_echo "$as_me:$LINENO:
+*** GTHREAD 2.0 is not required to build Funk2, but the Gthread development headers
+*** are not installed, so GTHREAD support will not be compiled into Funk2.  The
+*** latest version of Gthread is always available at http://www.gtk.org" >&5
+$as_echo "$as_me:
+*** GTHREAD 2.0 is not required to build Funk2, but the Gthread development headers
+*** are not installed, so GTHREAD support will not be compiled into Funk2.  The
+*** latest version of Gthread is always available at http://www.gtk.org" >&6;}
+else
+	GTHREAD_CFLAGS=$pkg_cv_GTHREAD_CFLAGS
+	GTHREAD_LIBS=$pkg_cv_GTHREAD_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+
+cat >>confdefs.h <<\_ACEOF
+#define F2__GTHREAD_SUPPORTED 1
 _ACEOF
 
 fi
@@ -20428,11 +20526,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20431: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20529: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:20435: \$? = $ac_status" >&5
+   echo "$as_me:20533: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -20527,11 +20625,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20530: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20628: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20534: \$? = $ac_status" >&5
+   echo "$as_me:20632: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20579,11 +20677,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:20582: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:20680: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:20586: \$? = $ac_status" >&5
+   echo "$as_me:20684: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
